# Generated by Django 4.1.1 on 2023-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.IntegerField(),
        ),
    ]
