# Generated by Django 4.1.1 on 2023-03-19 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_edited_post_edited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.UUIDField()),
                ('user_like', models.UUIDField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
