# Generated by Django 4.1.1 on 2023-03-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_like',
            new_name='user_id',
        ),
    ]
